config/routes.rb
Rails.application.routes.draw do

  resources :evenements, :has_many => :photos

  resources :audios do
    member do
      get 'audio_download' => 'audios#audio_download', as: :audio_download
    end
  end

  
  resources :categorie_posts

  resources :posts do
  member do
    get "vote"
  end
end

  resources :comments

  resources :categorie_audios

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions",
                                   passwords: "users/passwords",
                                   omniauth_callbacks: "users/omniauth_callbacks"},
             skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end
  root 'welcome#index'
  get '/audiotheque' => 'welcome#audiotheque', as: :audiotheque
  get '/principes' => 'welcome#principes', as: :principes

end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Home", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tazawoudou choubane <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Historique", '#' %></li>
          <li class="divider"></li>
          <li><%= link_to "Principes", '#' %></li>
          <li class="divider"></li>
          <li><%= link_to "Comissions", '#' %></li>
          <li class="divider"></li>
          <li><%= link_to "Organigramme", '#' %></li>
        </ul>
      </li>
      <li><%= link_to "Enseignement", posts_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mediatheque <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Audiotheque", audiotheque_path %></li>
          <li><%= link_to "Photheque", audiotheque_path %></li>
          <li><%= link_to "Videotheque", audiotheque_path %></li>
        </ul>
      </li>
      <li><a href="#">Evenement</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/elements/_player.html.erb
<div class="example">

  <div class="player">
    <div class="pl"></div>
    <div class="title"></div>
    <div class="artist"></div>
    <div class="cover"></div>
    <div class="controls">
      <div class="play"></div>
      <div class="pause"></div>
      <div class="rew"></div>
      <div class="fwd"></div>
    </div>
    <div class="volume"></div>
    <div class="tracker"></div>
  </div>
  <ul class="playlist">
    <% @audios.each do |audio| %>
    <li audiourl="<%= audio.piste %>" cover="<%= audio.image.url(:thumb) %>" artist="Artist 1"><%= audio.author %>
      <a href="#">Download</a></li>
    <% end %>

  </ul>

</div>

<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>