config/routes.rb
Rails.application.routes.draw do

  resources :evenements, :has_many => :photos

  resources :audios do
    member do
      get 'audio_download' => 'audios#audio_download', as: :audio_download
    end
  end

  
  resources :categorie_posts

  resources :posts do
  member do
    get "vote"
  end
end

  resources :comments

  resources :categorie_audios

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions",
                                   passwords: "users/passwords",
                                   omniauth_callbacks: "users/omniauth_callbacks"},
             skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end
  root 'welcome#index'
  get '/audiotheque' => 'welcome#audiotheque', as: :audiotheque
  get '/principes' => 'welcome#principes', as: :principes

end

app/models/categorie_post.rb
class CategoriePost < ActiveRecord::Base
  belongs_to :user
  has_many :posts
end

app/controllers/categorie_posts_controller.rb
class CategoriePostsController < InheritedResources::Base

    #->Prelang (scaffolding:rails/scope_to_user)
    before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

    before_action :set_categorie_post, only: [:show, :edit, :update, :destroy]

    # GET /categorie_posts
    # GET /categorie_posts.json
    def index
      @categorie_posts = CategoriePost.all
    end

    # GET /categorie_posts/1
    # GET /categorie_posts/1.json
    def show
    end

    # GET /categorie_posts/new
    def new
      @categorie_post = CategoriePost.new
    end

    # GET /categorie_posts/1/edit
    def edit
    end

    # POST /categorie_posts
    # POST /categorie_posts.json
    def create
      @categorie_post = CategoriePost.new(categorie_post_params)
      @categorie_post.user = current_user

      respond_to do |format|
        if @categorie_post.save
          format.html { redirect_to @categorie_post, notice: 'Categorie post was successfully created.' }
          format.json { render :show, status: :created, location: @categorie_post }
        else
          format.html { render :new }
          format.json { render json: @categorie_post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /categorie_posts/1
    # PATCH/PUT /categorie_posts/1.json
    def update
      respond_to do |format|
        if @categorie_post.update(categorie_post_params)
          format.html { redirect_to @categorie_post, notice: 'Categorie post was successfully updated.' }
          format.json { render :show, status: :ok, location: @categorie_post }
        else
          format.html { render :edit }
          format.json { render json: @categorie_post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /categorie_posts/1
    # DELETE /categorie_posts/1.json
    def destroy
      @categorie_post.destroy
      respond_to do |format|
        format.html { redirect_to categorie_posts_url, notice: 'Categorie post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorie_post
      @categorie_post = CategoriePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorie_post_params
      params.require(:categorie_post).permit(:name, :description, :user_id)
    end

end

app/helpers/categorie_posts_helper.rb
module CategoriePostsHelper
end

app/views/categorie_posts/_form.html.erb
<%= simple_form_for @categorie_post do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-area form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-sm-offset-3 col-sm-9'>
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  categorie_posts_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/categorie_posts/edit.html.erb
<%- model_class = CategoriePost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categorie_posts/index.html.erb
<%- model_class = CategoriePost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categorie_posts.each do |categorie_post| %>
      <tr>
        <td><%= categorie_post.id %></td>
          <td><%= categorie_post.name %></td>
          <td><%= categorie_post.description %></td>
          <td><%= categorie_post.user_id %></td>
        <td><%=l categorie_post.created_at, format: :long %></td>
        <td>
          <%= link_to categorie_post_path(categorie_post), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_categorie_post_path(categorie_post), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to categorie_post_path(categorie_post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_categorie_post_path,
            :class => 'btn btn-primary' %>

app/views/categorie_posts/new.html.erb
<%- model_class = CategoriePost -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categorie_posts/show.html.erb
<%- model_class = CategoriePost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @categorie_post.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @categorie_post.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:user_id) %></dt>
      <dd><pre class="prettyprint"><%= @categorie_post.user_id %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categorie_posts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_categorie_post_path(@categorie_post), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              categorie_post_path(@categorie_post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>