config/routes.rb
Rails.application.routes.draw do

  resources :evenements, :has_many => :photos

  resources :audios do
    member do
      get 'audio_download' => 'audios#audio_download', as: :audio_download
    end
  end

  
  resources :categorie_posts

  resources :posts do
  member do
    get "vote"
  end
end

  resources :comments

  resources :categorie_audios

  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions",
                                   passwords: "users/passwords",
                                   omniauth_callbacks: "users/omniauth_callbacks"},
             skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end
  root 'welcome#index'
  get '/audiotheque' => 'welcome#audiotheque', as: :audiotheque
  get '/principes' => 'welcome#principes', as: :principes

end

app/models/evenement.rb
class Evenement < ActiveRecord::Base
  belongs_to :user
  has_many :photos, as: :imageable
end

app/controllers/evenements_controller.rb
class EvenementsController < InheritedResources::Base
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/views/evenements/_form.html.erb
<%= simple_form_for(@evenement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titre %>
    <%= f.input :date_event %>
    <%= f.input :lieu %>
    <%= f.input :details %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/evenements/edit.html.erb
<h1>Editing evenement</h1>

<%= render 'form' %>

<%= link_to 'Show', @evenement %> |
<%= link_to 'Back', evenements_path %>

app/views/evenements/index.html.erb
<h1>Listing evenements</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Date event</th>
      <th>Lieu</th>
      <th>Details</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evenements.each do |evenement| %>
      <tr>
        <td><%= evenement.titre %></td>
        <td><%= evenement.date_event %></td>
        <td><%= evenement.lieu %></td>
        <td><%= evenement.details %></td>
        <td><%= evenement.user %></td>
        <td><%= link_to 'Show', evenement %></td>
        <td><%= link_to 'Edit', edit_evenement_path(evenement) %></td>
        <td><%= link_to 'Destroy', evenement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evenement', new_evenement_path %>

app/views/evenements/new.html.erb
<h1>New evenement</h1>

<%= render 'form' %>

<%= link_to 'Back', evenements_path %>

app/views/evenements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @evenement.titre %>
</p>

<p>
  <strong>Date event:</strong>
  <%= @evenement.date_event %>
</p>

<p>
  <strong>Lieu:</strong>
  <%= @evenement.lieu %>
</p>

<p>
  <strong>Details:</strong>
  <%= @evenement.details %>
</p>

<p>
  <strong>User:</strong>
  <%= @evenement.user %>
</p>

<%= link_to 'Edit', edit_evenement_path(@evenement) %> |
<%= link_to 'Back', evenements_path %>